#激活使用哪一个配置文件
spring:
  profiles:
    active: dev
  # 配置jsp页面访问路径的前缀和后缀
    #前端视图展示采用JSP
  mvc:
     view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
  #配置编码过滤器
  http:
      encoding:
          chaset: utf-8
          enabled: true  #default true
          force: true
  #配置(数据源)数据库连接配置
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webblog
  #配置redis缓存数据库
#  redis:
#    host: localhost
#    port: 6379
  #redis哨兵模式配置
#  redis:
#    sentinel:
#      master: mymaster
#      nodes: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381


#配置mybatis映射文件所在路径
mybatis:
  mapper-locations: classpath:com/yj/webblog/mapping/*.xml


boot:
  name: 湖北
  location: 武汉

